### ISSUE TITLE
DDL has issues creating employees_projects

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#15]
```
Error: ER_CANT_CREATE_TABLE: Can't create table `cs340_humberj`.`employees_projects` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Pool.js:199:23)
    at /nfs/stak/users/humberj/cs340-dbb-step4/app.js:47:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/app.js:43:5)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlMessage: 'Can\'t create table `cs340_humberj`.`employees_projects` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sqlState: 'HY000',
  index: 0,
  sql: '\n' +
    '\n' +
    '-- -----------------------------------------------------\n' +
    '-- Table employees_projects\n' +
    '-- -----------------------------------------------------\n' +
    'CREATE TABLE IF NOT EXISTS employees_projects (\n' +
    '  employee_id INT UNSIGNED NOT NULL,\n' +
    '  project_id INT UNSIGNED NOT NULL,\n' +
    '  date_of_work DATE NOT NULL,\n' +
    '  number_hours TINYINT UNSIGNED NOT NULL,\n' +
    '  PRIMARY KEY (employee_id,project_id,date_of_work), -- I changed the primary key to be a new field, "entry_id", since there can be multiple entries with the same (employee_id,project_id)\n' +
    '  CONSTRAINT fk_employees_has_projects_employees1\n' +
    '    FOREIGN KEY (employee_id)\n' +
    '    REFERENCES employees (employee_id)\n' +
    '    ON DELETE NO ACTION\n' +
    '    ON UPDATE NO ACTION,\n' +
    '  CONSTRAINT fk_employees_has_projects_projects1\n' +
    '    FOREIGN KEY (project_id)\n' +
    '    REFERENCES projects (project_id)\n' +
    '    ON DELETE NO ACTION\n' +
    '    ON UPDATE NO ACTION,\n' +
    '  CONSTRAINT err_duplicate_input UNIQUE(employee_id,project_id,date_of_work),\n' +
    '  CONSTRAINT over_max_hours_in_day CHECK(number_hours <= 24)\n' +
    ');'
}
```

**Comment by nairnhoc** [comment]
What generates this error? Running `source DDL.sql` appears to work for me in CL mySQL. Is this from the queries generated by `app.js`?

**Comment by CupofJosiah** [comment]
Yeah. Currently having `app.js` import `DDL.sql` then separate it into the individual queries. Then it sends them to mysql one by one using `db.pool.query`. You can see the raw query sent to mariaDB in the error message,
```
'\n' +
    '\n' +
    '-- -----------------------------------------------------\n' +
    '-- Table employees_projects\n' +
    '-- -----------------------------------------------------\n' +
    'CREATE TABLE IF NOT EXISTS employees_projects (\n' +
    '  employee_id INT UNSIGNED NOT NULL,\n' +
    '  project_id INT UNSIGNED NOT NULL,\n' +
    '  date_of_work DATE NOT NULL,\n' +
    '  number_hours TINYINT UNSIGNED NOT NULL,\n' +
    '  PRIMARY KEY (employee_id,project_id,date_of_work), -- I changed the primary key to be a new field, "entry_id", since there can be multiple entries with the same (employee_id,project_id)\n' +
    '  CONSTRAINT fk_employees_has_projects_employees1\n' +
    '    FOREIGN KEY (employee_id)\n' +
    '    REFERENCES employees (employee_id)\n' +
    '    ON DELETE NO ACTION\n' +
    '    ON UPDATE NO ACTION,\n' +
    '  CONSTRAINT fk_employees_has_projects_projects1\n' +
    '    FOREIGN KEY (project_id)\n' +
    '    REFERENCES projects (project_id)\n' +
    '    ON DELETE NO ACTION\n' +
    '    ON UPDATE NO ACTION,\n' +
    '  CONSTRAINT err_duplicate_input UNIQUE(employee_id,project_id,date_of_work),\n' +
    '  CONSTRAINT over_max_hours_in_day CHECK(number_hours <= 24)\n' +
    ');'
```

**Comment by CupofJosiah** [comment]
`app.js` was performing each query synchronously, causing an error with tables not existing yet when attempting to create tables. The code now allows each query to finish before running the next
