### ISSUE TITLE
DDL has issues creating salaries table

### ISSUE THREAD

**Issue by CupofJosiah** [CS340-Database-Beavers/cs340-dbb-step4#16]
```
Error: ER_CANT_CREATE_TABLE: Can't create table `cs340_humberj`.`salaries` (errno: 150 "Foreign key constraint is incorrectly formed")
    at Query.Sequence._packetToError (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Pool.query (/nfs/stak/users/humberj/cs340-dbb-step4/node_modules/mysql/lib/Pool.js:199:23)
    at /nfs/stak/users/humberj/cs340-dbb-step4/app.js:47:13
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/nfs/stak/users/humberj/cs340-dbb-step4/app.js:43:5)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ER_CANT_CREATE_TABLE',
  errno: 1005,
  sqlMessage: 'Can\'t create table `cs340_humberj`.`salaries` (errno: 150 "Foreign key constraint is incorrectly formed")',
  sqlState: 'HY000',
  index: 0,
  sql: '\n' +
    '\n' +
    '-- -----------------------------------------------------\n' +
    '-- Table salaries\n' +
    '-- -----------------------------------------------------\n' +
    'CREATE TABLE IF NOT EXISTS salaries (\n' +
    '  salary_id INT UNSIGNED NOT NULL AUTO_INCREMENT,\n' +
    '  effective_date DATE NOT NULL,\n' +
    '  pay_amount DECIMAL(10,2) UNSIGNED NOT NULL,\n' +
    '  employee_id INT UNSIGNED NULL,\n' +
    '  PRIMARY KEY (salary_id),\n' +
    '  CONSTRAINT fk_salaries_employees1\n' +
    '    FOREIGN KEY (employee_id)\n' +
    '    REFERENCES employees (employee_id)\n' +
    '    ON DELETE NO ACTION\n' +
    '    ON UPDATE NO ACTION,\n' +
    '  CONSTRAINT err_cannot_overide_entry UNIQUE(employee_id,effective_date)\n' +
    ');'
}
```

**Comment by CupofJosiah** [comment]
`app.js` was performing each query synchronously, causing an error with tables not existing yet when attempting to create tables. The code now allows each query to finish before running the next
